# static pose covariances matrix
cov:
    static_pose_cov: [   0.1,     0,     0,     0,     0,     0,
                           0,   0.1,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,     0,
                           0,     0,     0,     0,     0,   0.1]
